### ISSUE TITLE
woff2 not uploading to h5p

### ISSUE THREAD

**Issue by RGunning** [h5p/font-awesome#1]
Using h5p on wordpress
404 GET error `uploads/h5p/libraries/FontAwesome-4.5/fontawesome-webfont.woff2?v=4.5.0`

woff2 file not in directory. H5P does not accept woff2 files

**Comment by icc** [comment]
Thank you for reporting. This was fixed in h5p/h5p-php-library@6bfffbc, and will be part of the next version of the plugin.
